apiVersion: v1
kind: Namespace
metadata:
  name: ${VSCODE_NAMESPACE}
  labels:
    app.kubernetes.io/name: vscode-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vscode-server-ingress-helper
  namespace: ${VSCODE_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~ ^/stable|insiders|static|callback|web-extension-resource {
          proxy_set_header Host $host;

          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Auth-Request-Redirect $scheme://$host$request_uri;

          auth_request /oauth2/auth;
          error_page 401 = ${VSCODE_INGRESS_AUTH_SIGNIN};

          auth_request_set $user   $upstream_http_x_auth_request_user;
          auth_request_set $email  $upstream_http_x_auth_request_email;
          auth_request_set $token  $upstream_http_x_auth_request_access_token;
          proxy_set_header X-User  $user;
          proxy_set_header X-Email $email;
          proxy_set_header X-Access-Token $token;

          rewrite $uri /$user$uri;
      }
    external-dns.alpha.kubernetes.io/hostname: ${ACCOUNT_HOSTNAME}
    external-dns.alpha.kubernetes.io/target: ${VSCODE_HOSTNAME}
    external-dns.alpha.kubernetes.io/ttl: "600"
    cert-manager.io/cluster-issuer: ${VSCODE_CERT_CLUSTER_ISSUER}
spec:
  ingressClassName: ${NGINX_INGRESS_CLASS}
  tls:
    - hosts:
        - ${VSCODE_HOSTNAME}
      secretName: vscode-server-ingress-tls
  rules:
    - host: ${VSCODE_HOSTNAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vscode-server-helper
                port:
                  number: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vscode-server-helper
  name: vscode-server-helper
  namespace: ${VSCODE_NAMESPACE}
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: vscode-server-helper
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  namespace: ${VSCODE_NAMESPACE}
  name: vscode-server-helper # by convention, use the name of the service as a prefix for the name of the EndpointSlice
  labels:
    # You should set the "kubernetes.io/service-name" label. Set its value to match the name of the service
    kubernetes.io/service-name: vscode-server-helper
addressType: IPv4
ports:
  - name: vscode-server-helper
    appProtocol: http
    protocol: TCP
    port: 8000
endpoints:
  - addresses:
      - "${EXTERNAL_IP}" # the IP addresses in this list can appear in any order
---
kind: Endpoints
apiVersion: v1
metadata:
  namespace: ${VSCODE_NAMESPACE}
  name: vscode-server-helper
subsets:
  - addresses:
      - ip: "${EXTERNAL_IP}"
    ports:
      - port: 8000
        name: vscode-server-helper
