apiVersion: v1
kind: Namespace
metadata:
  name: ${ACCOUNT_NAMESPACE}
  labels:
    app.kubernetes.io/name: ${ACCOUNT_NAMESPACE}
---
apiVersion: v1
kind: Service
metadata:
  name: ${ACCOUNT_NAMESPACE}
  namespace: ${ACCOUNT_NAMESPACE}
  labels:
    app.kubernetes.io/name: ${ACCOUNT_NAMESPACE}
spec:
  type: ClusterIP
  ports:
    - appProtocol: http
      name: http
      port: 8000
      targetPort: http
  selector:
    app.kubernetes.io/name: ${ACCOUNT_NAMESPACE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ACCOUNT_NAMESPACE}
  namespace: ${ACCOUNT_NAMESPACE}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ${ACCOUNT_NAMESPACE}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${ACCOUNT_NAMESPACE}
    spec:
      serviceAccountName: ${ACCOUNT_NAMESPACE}
      containers:
        - name: dind-daemon
          image: docker:dind
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: ${DIND_CPU_MAX}
              memory: ${DIND_MEM_MAX}
            requests:
              cpu: ${DIND_CPU_REQUEST}
              memory: ${DIND_MEM_REQUEST}
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
            - name: docker-graph-certs
              mountPath: /certs
            - name: docker-graph-run
              mountPath: /var/run
        - name: ${ACCOUNT_NAMESPACE}
          image: ${VSCODE_SERVER_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - mountPath: /usr/share/vscode-server
              name: vscode-server-data
            - mountPath: /home/vscode-server/sources
              name: vscode-server-sources
            - mountPath: /certs
              name: docker-graph-certs
            - mountPath: /var/run
              name: docker-graph-run
          env:
            - name: VSCODE_KEYRING_PASS
              value: "${VSCODE_KEYRING_PASS}"
            - name: VSCODE_SERVER_DATA_DIR
              value: "/usr/share/vscode-server"
          envFrom:
            - configMapRef:
                name: ${ACCOUNT_NAMESPACE}
          resources:
            limits:
              cpu: "${VSCODE_CPU_MAX}"
              memory: "${VSCODE_MEM_MAX}"
            requests:
              cpu: "${VSCODE_CPU_REQUEST}"
              memory: "${VSCODE_MEM_REQUEST}"
      volumes:
        - name: docker-graph-run
          emptyDir: {}
        - name: docker-graph-certs
          emptyDir: {}
        - name: docker-graph-storage
          emptyDir: {}
        - name: vscode-server-data
          emptyDir: {}
        - name: vscode-server-sources
          persistentVolumeClaim:
            claimName: ${ACCOUNT_NAMESPACE}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ${ACCOUNT_NAMESPACE}
  name: ${ACCOUNT_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: ${VSCODE_PVC_SIZE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: ${ACCOUNT_NAMESPACE}
  name: ${ACCOUNT_NAMESPACE}
  namespace: ${ACCOUNT_NAMESPACE}
rules:
  - apiGroups:
      - ""
    resourceNames:
      - ${ACCOUNT_NAMESPACE}
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: ${ACCOUNT_NAMESPACE}
  name: ${ACCOUNT_NAMESPACE}
  namespace: ${ACCOUNT_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-nginx
subjects:
  - kind: ServiceAccount
    name: ${ACCOUNT_NAMESPACE}
    namespace: ${ACCOUNT_NAMESPACE}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ${ACCOUNT_NAMESPACE}
  name: ${ACCOUNT_NAMESPACE}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${ACCOUNT_NAMESPACE}
  namespace: ${ACCOUNT_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/secure-backends: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
#    nginx.ingress.kubernetes.io/auth-url: "${VSCODE_INGRESS_AUTH_URL}"
#    nginx.ingress.kubernetes.io/auth-signin: "${VSCODE_INGRESS_AUTH_SIGNIN}"
#    cert-manager.io/cluster-issuer: "${VSCODE_CERT_CLUSTER_ISSUER}"
spec:
  ingressClassName: ${NGINX_INGRESS_CLASS}
  tls:
    - hosts:
        - ${VSCODE_HOSTNAME}
      secretName: vscode-server-ingress-tls
  rules:
    - host: ${VSCODE_HOSTNAME}
      http:
        paths:
          - path: /${ACCOUNT_NAMESPACE}/(.*)
            pathType: Prefix
            backend:
              service:
                name: ${ACCOUNT_NAMESPACE}
                port:
                  number: 8000
---
${ACCOUNT_CONFIGMAP}
---
${ACCOUNT_SECRET}
---
${INGRESS_SECRET_TLS}
