apiVersion: v1
kind: Namespace
metadata:
  name: ${ACCOUNT_NAMESPACE}
  labels:
    app.kubernetes.io/name: ${ACCOUNT_NAMESPACE}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ${ACCOUNT_NAMESPACE}
  name: vscode-server
---
apiVersion: v1
kind: Service
metadata:
  name: vscode-server
  namespace: ${ACCOUNT_NAMESPACE}
  labels:
    app.kubernetes.io/name: vscode-server
spec:
  type: ClusterIP
  ports:
    - appProtocol: http
      name: http
      port: 8000
      targetPort: http
  selector:
    app.kubernetes.io/name: vscode-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode-server
  namespace: ${ACCOUNT_NAMESPACE}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: vscode-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vscode-server
    spec:
      serviceAccountName: vscode-server
      containers:
        - name: dind-daemon
          image: docker:dind
          imagePullPolicy: Always
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: ${DIND_CPU_MAX}
              memory: ${DIND_MEM_MAX}
            requests:
              cpu: ${DIND_CPU_REQUEST}
              memory: ${DIND_MEM_REQUEST}
          volumeMounts:
            - name: vscode-server-volume
              mountPath: /var/lib/docker
              subPath: vscode-server-docker
            - name: docker-graph-run
              mountPath: /var/run
            - name: vscode-server-volume
              mountPath: /certs
              subPath: vscode-server-cert
        - name: vscode-server
          image: ${VSCODE_SERVER_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - mountPath: /usr/share/vscode-server
              name: vscode-server-volume
              subPath: vscode-server-data
            - mountPath: /home/vscode-server
              name: vscode-server-volume
              subPath: vscode-server-home
            - mountPath: /certs
              name: vscode-server-volume
              subPath: vscode-server-cert
            - mountPath: /var/run
              name: docker-graph-run
          env:
            - name: VSCODE_KEYRING_PASS
              value: "${VSCODE_KEYRING_PASS}"
            - name: VSCODE_SERVER_DATA_DIR
              value: "/usr/share/vscode-server"
          envFrom:
            - configMapRef:
                name: ${ACCOUNT_NAMESPACE}
          resources:
            limits:
              cpu: "${VSCODE_CPU_MAX}"
              memory: "${VSCODE_MEM_MAX}"
            requests:
              cpu: "${VSCODE_CPU_REQUEST}"
              memory: "${VSCODE_MEM_REQUEST}"
      volumes:
        - name: docker-graph-run
          emptyDir: {}
        - name: vscode-server-volume
          persistentVolumeClaim:
            claimName: pvc-vscode-server-${ACCOUNT_NAMESPACE}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ${ACCOUNT_NAMESPACE}
  name: pvc-vscode-server-${ACCOUNT_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: ${VSCODE_PVC_SIZE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: vscode-server
  name: vscode-server
  namespace: ${ACCOUNT_NAMESPACE}
rules:
  - apiGroups:
      - ""
    resourceNames:
      - ${ACCOUNT_NAMESPACE}
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: vscode-server
  name: vscode-server
  namespace: ${ACCOUNT_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vscode-server
subjects:
  - kind: ServiceAccount
    name: vscode-server
    namespace: ${ACCOUNT_NAMESPACE}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-vscode-server-${ACCOUNT_NAMESPACE}
  namespace: ${ACCOUNT_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/stable|insiders|static|callback|web-extension-resource /${ACCOUNT_NAMESPACE}$uri break;

      auth_request_set $user   $upstream_http_x_auth_request_user;
      auth_request_set $email  $upstream_http_x_auth_request_email;
      auth_request_set $token  $upstream_http_x_auth_request_access_token;
      proxy_set_header X-User  $user;
      proxy_set_header X-Email $email;
      proxy_set_header X-Access-Token $token;
      proxy_set_header Accept-Encoding "";
      proxy_set_header X-Forwarded-Prefix ${ACCOUNT_NAMESPACE};
      proxy_set_header X-Forwarded-Uri $request_uri;
      sub_filter_types text/html text/html;
      sub_filter_once off;
      sub_filter 'href="/' 'href="/${ACCOUNT_NAMESPACE}/';
      sub_filter 'src="/' 'src="/${ACCOUNT_NAMESPACE}/';
      sub_filter 'href=\'/' 'href=\'/${ACCOUNT_NAMESPACE}/';
      sub_filter 'src=\'/' 'src=\'/${ACCOUNT_NAMESPACE}/';
#    external-dns.alpha.kubernetes.io/hostname: ${ACCOUNT_HOSTNAME}
#    external-dns.alpha.kubernetes.io/target: ${VSCODE_HOSTNAME}
#    external-dns.alpha.kubernetes.io/ttl: '600'
    nginx.ingress.kubernetes.io/auth-url: "${VSCODE_INGRESS_AUTH_URL}"
    nginx.ingress.kubernetes.io/auth-signin: "${VSCODE_INGRESS_AUTH_SIGNIN}"
#    cert-manager.io/cluster-issuer: "${VSCODE_CERT_CLUSTER_ISSUER}"
spec:
  ingressClassName: ${NGINX_INGRESS_CLASS}
  tls:
    - hosts:
        - ${VSCODE_HOSTNAME}
      secretName: vscode-server-ingress-tls
  rules:
    - host: ${VSCODE_HOSTNAME}
      http:
        paths:
          - path: /${ACCOUNT_NAMESPACE}/(.*)
            pathType: Prefix
            backend:
              service:
                name: vscode-server
                port:
                  number: 8000
---
${ACCOUNT_CONFIGMAP}
---
${ACCOUNT_SECRET}
---
${INGRESS_SECRET_TLS}
