apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: vscode-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: redis
  name: redis
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      initContainers:
        - name: config
          image: redis:6-alpine3.17
          command: ["sh", "/tmp/redis/init.sh"]
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis/
            - name: redis-configmap
              mountPath: /tmp/redis/
      containers:
        - name: redis
          image: redis:6-alpine3.17
          command: ["redis-server"]
          args: ["/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: pvc-redis
              mountPath: /data
            - name: redis-config
              mountPath: /etc/redis/
            - name: redis-tls
              mountPath: /usr/local/etc/redis/tls
          resources:
            limits:
              cpu: 500m
              memory: 640Mi
            requests:
              cpu: 100m
              memory: 200Mi
      volumes:
        - name: redis-config
          emptyDir: {}
        - name: redis-configmap
          configMap:
            name: redis-config
        - name: redis-tls
          secret:
            secretName: redis-tls
  volumeClaimTemplates:
    - metadata:
        name: pvc-redis
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: redis
  name: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app.kubernetes.io/name: redis
