name: Build Docker image CI

on:
  push:
    tags:
      - docker-ci
      - v*
env:
  VSCODE_SERVER_REGISTRY: ${{ vars.VSCODE_SERVER_REGISTRY }}
  GIT_ACTOR: ${{ github.actor }}
  GIT_PAT: ${{ secrets.GIT_PAT }}
  GITHUB_TOKEN: ${{ github.token }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2.2.1
        with:
          version: latest
          endpoint: builders
          use: true

      - name: Build, tag, and push the image to docker registry
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}

          if [ "${VSCODE_SERVER_REGISTRY}" == "ghcr.io" ]; then
            echo $GIT_PAT | docker login ghcr.io -u ${GIT_ACTOR} --password-stdin
          else
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          fi

          ./buildx.sh
